# GET https://serene-dawn-47935.herokuapp.com/api/restaurants?page=s&perPage=5&borough=String

# GET http://localhost:8080/api/restaurants/5eb3d668b31de5d588f42936

# POST https://serene-dawn-47935.herokuapp.com/api/restaurants
# Content-Type: application/json

# # {
# #     "address": {
# #         "building": "testString",
# #         "coord": [20, 20],
# #         "street": "Strinng",
# #         "zipcode": "String"
# #     }
# # }

# {
#     "address": {
#         "building": "testingliveString",
#         "coord": [20, 20],
#         "street": "testingliveString",
#         "zipcode": "testingliveString"
#     },
#     "borough": "testingliveString",
#     "cuisine": "testingliveString",
#     "grades": [{
#         "date": "2014-06-10",
#         "grade": "testingliveString",
#         "score": 5
#     }],
#     "name": "testingliveString",
#     "restaurant_id": "testingliveString"
# }


# PUT https://serene-dawn-47935.herokuapp.com/api/restaurants/614538276c4ca39d7d317b73
# Content-Type: application/json

# {
#     "address": {
#         "building": "liveupdated",
#         "coord": [20, 20],
#         "street": "liveupdated",
#         "zipcode": "liveupdated"
#     },
#     "borough": "liveupdated",
#     "cuisine": "liveupdated",
#     "grades": [{
#         "date": "2014-06-10",
#         "grade": "liveupdated",
#         "score": 5
#     }],
#     "name": "liveupdated",
#     "restaurant_id": "liveupdated"
# }

# DELETE https://serene-dawn-47935.herokuapp.com/api/restaurants/614538276c4ca39d7d317b73