GET http://localhost:8080/api/restaurants?page=1&perPage=5&borough=String

# GET http://localhost:8080/api/restaurants/5eb3d668b31de5d588f42936

# POST https://serene-dawn-47935.herokuapp.com/api/restaurants
# Content-Type: application/json

# # {
# #     "address": {
# #         "building": "testString",
# #         "coord": [20, 20],
# #         "street": "Strinng",
# #         "zipcode": "String"
# #     }
# # }

# {
#     "address": {
#         "building": "liveString",
#         "coord": [20, 20],
#         "street": "liveString",
#         "zipcode": "liveString"
#     },
#     "borough": "liveString",
#     "cuisine": "liveString",
#     "grades": [{
#         "date": "2014-06-10",
#         "grade": "liveString",
#         "score": 5
#     }],
#     "name": "liveString",
#     "restaurant_id": "liveString"
# }


# PUT http://localhost:8080/api/restaurants/5eb3d668b31de5d588f42936
# Content-Type: application/json

# {
#     "address": {
#         "building": "update",
#         "coord": [20, 20],
#         "street": "update",
#         "zipcode": "update"
#     },
#     "borough": "update",
#     "cuisine": "update",
#     "grades": [{
#         "date": "2014-06-10",
#         "grade": "update",
#         "score": 5
#     }],
#     "name": "update",
#     "restaurant_id": "update"
# }

# DELETE https://serene-dawn-47935.herokuapp.com/api/restaurants/6143828fe8818695d27664d5